"""
Yotter settings for config project.
Generated by 'yotter startproject' using Yotter version.
"""
from pathlib import Path
from telebot import custom_filters

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Place your bot token here
BOT_TOKEN = ''

LOGGIN_LEVEL = 'info'
DEFAULT_PARSE_MODE = None
MIDDLEWARED_ENABLED = True

# Start bot with polling and infinity polling methods
POLLING_ENABLE = True
POLLING_INF = False
POLLING_TIMEOUT = 20
POLLING_SKIP_PENDING = False

# Allowed updates received in bot
POLLING_ALLOW_UPDATES = [
    "message",
    "edited_message",
    "channel_post",
    "edited_channel_post",
    "inline_query",
    "chosen_inline_result",
    "callback_query",
    "shipping_query",
    "pre_checkout_query",
    "poll",
    "poll_answer",
    "my_chat_member",
    "chat_member",
    "chat_join_request"
]

# Add custom filters to bot
CUSTOM_FILTERS = [
    custom_filters.IsAdminFilter,
]

# Start bot with webhook method
WEBHOOKS_ENABLE = False
WEBHOOK_HOST = ''
WEBHOOK_PORT = 8080
WEBHOOK_LISTEN = '0.0.0.0'
WEBHOOK_SSL_CERT = None
WEBHOOK_SSL_PRIV = None

# Enable this pref for restart bot, if getting changes in code
RESTART_ON_CHANGE = False
